@echo off
setlocal EnableExtensions EnableDelayedExpansion
title CodaLoader

cd /d "%~dp0"

set "CODA_JAR="
for %%F in ("CodaLoader-*.jar") do (
    if not defined CODA_JAR set "CODA_JAR=%%~fF"
)

if not defined CODA_JAR (
    echo.
    echo [CodaLoader] I cannot find CodaLoader-*.jar beside this launcher.
    echo [CodaLoader] Put Launch-CodaLoader.bat in the same folder as the CodaLoader JAR.
    echo.
    call :PauseIfNeeded
    exit /b 1
)

echo.
echo ============================================================
echo                     CodaLoader
echo ============================================================
echo [CodaLoader] Looking for Java 21 or newer...

set "JAVA_CMD="
set "CODA_JAVA_RESULT=%TEMP%\codaloader-java-%RANDOM%%RANDOM%.txt"
del /q "%CODA_JAVA_RESULT%" >nul 2>nul

powershell.exe -NoProfile -ExecutionPolicy Bypass -EncodedCommand JABFAHIAcgBvAHIAQQBjAHQAaQBvAG4AUAByAGUAZgBlAHIAZQBuAGMAZQAgAD0AIAAnAFMAaQBsAGUAbgB0AGwAeQBDAG8AbgB0AGkAbgB1AGUAJwAKAAoAZgB1AG4AYwB0AGkAbwBuACAAVABlAHMAdAAtAEMAbwBkAGEASgBhAHYAYQAoAFsAcwB0AHIAaQBuAGcAXQAkAGoAKQAgAHsACgAgACAAIAAgAGkAZgAgACgAWwBzAHQAcgBpAG4AZwBdADoAOgBJAHMATgB1AGwAbABPAHIAVwBoAGkAdABlAFMAcABhAGMAZQAoACQAagApACkAIAB7ACAAcgBlAHQAdQByAG4AIAAkAGYAYQBsAHMAZQAgAH0ACgAgACAAIAAgAGkAZgAgACgALQBuAG8AdAAgACgAVABlAHMAdAAtAFAAYQB0AGgAIAAtAEwAaQB0AGUAcgBhAGwAUABhAHQAaAAgACQAagAgAC0AUABhAHQAaABUAHkAcABlACAATABlAGEAZgApACkAIAB7ACAAcgBlAHQAdQByAG4AIAAkAGYAYQBsAHMAZQAgAH0ACgAKACAAIAAgACAAdAByAHkAIAB7AAoAIAAgACAAIAAgACAAIAAgACQAbwB1AHQAcAB1AHQAIAA9ACAAJgAgACQAagAgAC0AdgBlAHIAcwBpAG8AbgAgADIAPgAmADEACgAgACAAIAAgACAAIAAgACAAJABsAGkAbgBlACAAPQAgAFsAcwB0AHIAaQBuAGcAXQAoACQAbwB1AHQAcAB1AHQAIAB8ACAAUwBlAGwAZQBjAHQALQBPAGIAagBlAGMAdAAgAC0ARgBpAHIAcwB0ACAAMQApAAoAIAAgACAAIAAgACAAIAAgAGkAZgAgACgAJABsAGkAbgBlACAALQBtAGEAdABjAGgAIAAnAHYAZQByAHMAaQBvAG4AXABzACsAIgA/ACgAWwAwAC0AOQBdACsAKQAnACkAIAB7AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAcgBlAHQAdQByAG4AIAAoAFsAaQBuAHQAXQAkAE0AYQB0AGMAaABlAHMAWwAxAF0AIAAtAGcAZQAgADIAMQApAAoAIAAgACAAIAAgACAAIAAgAH0ACgAgACAAIAAgAH0AIABjAGEAdABjAGgAIAB7AH0ACgAKACAAIAAgACAAcgBlAHQAdQByAG4AIAAkAGYAYQBsAHMAZQAKAH0ACgAKAGYAdQBuAGMAdABpAG8AbgAgAFMAYQB2AGUALQBDAG8AZABhAEoAYQB2AGEAKABbAHMAdAByAGkAbgBnAF0AJABqACkAIAB7AAoAIAAgACAAIABbAEkATwAuAEYAaQBsAGUAXQA6ADoAVwByAGkAdABlAEEAbABsAFQAZQB4AHQAKAAkAGUAbgB2ADoAQwBPAEQAQQBfAEoAQQBWAEEAXwBSAEUAUwBVAEwAVAAsACAAJABqACkACgAgACAAIAAgAGUAeABpAHQAIAAwAAoAfQAKAAoAJABkAGkAcgBlAGMAdAAgAD0AIABAACgAKQAKAAoAaQBmACAAKAAkAGUAbgB2ADoASgBBAFYAQQBfAEgATwBNAEUAKQAgAHsACgAgACAAIAAgACQAZABpAHIAZQBjAHQAIAArAD0AIAAoAEoAbwBpAG4ALQBQAGEAdABoACAAJABlAG4AdgA6AEoAQQBWAEEAXwBIAE8ATQBFACAAJwBiAGkAbgBcAGoAYQB2AGEALgBlAHgAZQAnACkACgB9AAoACgAkAGMAbQBkACAAPQAgAEcAZQB0AC0AQwBvAG0AbQBhAG4AZAAgAGoAYQB2AGEALgBlAHgAZQAgAC0ARQByAHIAbwByAEEAYwB0AGkAbwBuACAAUwBpAGwAZQBuAHQAbAB5AEMAbwBuAHQAaQBuAHUAZQAKAGkAZgAgACgAJABjAG0AZAApACAAewAKACAAIAAgACAAJABkAGkAcgBlAGMAdAAgACsAPQAgACQAYwBtAGQALgBTAG8AdQByAGMAZQAKAH0ACgAKAGYAbwByAGUAYQBjAGgAIAAoACQAagAgAGkAbgAgACgAJABkAGkAcgBlAGMAdAAgAHwAIABTAGUAbABlAGMAdAAtAE8AYgBqAGUAYwB0ACAALQBVAG4AaQBxAHUAZQApACkAIAB7AAoAIAAgACAAIABpAGYAIAAoAFQAZQBzAHQALQBDAG8AZABhAEoAYQB2AGEAIAAkAGoAKQAgAHsACgAgACAAIAAgACAAIAAgACAAUwBhAHYAZQAtAEMAbwBkAGEASgBhAHYAYQAgACQAagAKACAAIAAgACAAfQAKAH0ACgAKACQAcgBvAG8AdABzACAAPQAgAEAAKAAKACAAIAAgACAAKABKAG8AaQBuAC0AUABhAHQAaAAgACQAZQBuAHYAOgBQAHIAbwBnAHIAYQBtAEYAaQBsAGUAcwAgACcASgBhAHYAYQAnACkALAAKACAAIAAgACAAKABKAG8AaQBuAC0AUABhAHQAaAAgACQAZQBuAHYAOgBQAHIAbwBnAHIAYQBtAEYAaQBsAGUAcwAgACcARQBjAGwAaQBwAHMAZQAgAEEAZABvAHAAdABpAHUAbQAnACkALAAKACAAIAAgACAAKABKAG8AaQBuAC0AUABhAHQAaAAgACQAZQBuAHYAOgBBAFAAUABEAEEAVABBACAAJwAuAG0AaQBuAGUAYwByAGEAZgB0AFwAcgB1AG4AdABpAG0AZQAnACkALAAKACAAIAAgACAAKABKAG8AaQBuAC0AUABhAHQAaAAgACQAZQBuAHYAOgBMAE8AQwBBAEwAQQBQAFAARABBAFQAQQAgACcATQBpAG4AZQBjAHIAYQBmAHQAIABMAGEAdQBuAGMAaABlAHIAJwApACwACgAgACAAIAAgACgASgBvAGkAbgAtAFAAYQB0AGgAIAAkAGUAbgB2ADoATABPAEMAQQBMAEEAUABQAEQAQQBUAEEAIAAnAFAAYQBjAGsAYQBnAGUAcwBcAE0AaQBjAHIAbwBzAG8AZgB0AC4ANAAyADkANwAxADIANwBEADYANABFAEMANgBfADgAdwBlAGsAeQBiADMAZAA4AGIAYgB3AGUAJwApACwACgAgACAAIAAgACcAQwA6AFwAWABiAG8AeABHAGEAbQBlAHMAXABNAGkAbgBlAGMAcgBhAGYAdAAgAEwAYQB1AG4AYwBoAGUAcgAnAAoAKQAKAAoAZgBvAHIAZQBhAGMAaAAgACgAJAByACAAaQBuACAAJAByAG8AbwB0AHMAKQAgAHsACgAgACAAIAAgAGkAZgAgACgAJAByACAALQBhAG4AZAAgACgAVABlAHMAdAAtAFAAYQB0AGgAIAAtAEwAaQB0AGUAcgBhAGwAUABhAHQAaAAgACQAcgApACkAIAB7AAoAIAAgACAAIAAgACAAIAAgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAoACcAWwBDAG8AZABhAEwAbwBhAGQAZQByAF0AIABDAGgAZQBjAGsAaQBuAGcAIAAnACAAKwAgACQAcgApAAoACgAgACAAIAAgACAAIAAgACAAZgBvAHIAZQBhAGMAaAAgACgAJABmACAAaQBuACAAKABHAGUAdAAtAEMAaABpAGwAZABJAHQAZQBtACAALQBMAGkAdABlAHIAYQBsAFAAYQB0AGgAIAAkAHIAIAAtAEYAaQBsAHQAZQByACAAagBhAHYAYQAuAGUAeABlACAALQBGAGkAbABlACAALQBSAGUAYwB1AHIAcwBlACAALQBFAHIAcgBvAHIAQQBjAHQAaQBvAG4AIABTAGkAbABlAG4AdABsAHkAQwBvAG4AdABpAG4AdQBlACkAKQAgAHsACgAgACAAIAAgACAAIAAgACAAIAAgACAAIABpAGYAIAAoAFQAZQBzAHQALQBDAG8AZABhAEoAYQB2AGEAIAAkAGYALgBGAHUAbABsAE4AYQBtAGUAKQAgAHsACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAFMAYQB2AGUALQBDAG8AZABhAEoAYQB2AGEAIAAkAGYALgBGAHUAbABsAE4AYQBtAGUACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAB9AAoAIAAgACAAIAAgACAAIAAgAH0ACgAgACAAIAAgAH0ACgB9AAoACgBlAHgAaQB0ACAAMQA=

if exist "%CODA_JAVA_RESULT%" (
    set /p "JAVA_CMD="<"%CODA_JAVA_RESULT%"
)
del /q "%CODA_JAVA_RESULT%" >nul 2>nul

if not defined JAVA_CMD (
    echo.
    echo [CodaLoader] I could not find Java 21 or newer.
    echo [CodaLoader] Java 26 is supported. If it is installed outside the usual folders,
    echo [CodaLoader] set JAVA_HOME to that installation and run this launcher again.
    echo.
    call :PauseIfNeeded
    exit /b 1
)

if not exist "run" mkdir "run"
if not exist "run\mods" mkdir "run\mods"

echo [CodaLoader] Java:     !JAVA_CMD!
"!JAVA_CMD!" -version
echo [CodaLoader] Launcher: %~nx0
echo [CodaLoader] JAR:      %CODA_JAR%
echo [CodaLoader] Game dir: %CD%\run
echo.

"!JAVA_CMD!" -jar "%CODA_JAR%" "%CD%\run"
set "CODA_EXIT=!ERRORLEVEL!"

echo.
if "!CODA_EXIT!"=="0" (
    echo [CodaLoader] Process finished normally.
) else (
    echo [CodaLoader] Process exited with code !CODA_EXIT!.
)

echo.
call :PauseIfNeeded
exit /b !CODA_EXIT!

:PauseIfNeeded
if not defined CODA_NO_PAUSE pause
exit /b 0
